CREATE TABLE EMPLOYEE(
EMPLOYEE_ID TEXT,
EMPLOYEE_NAME TEXT,
EMPLOYEE_AGE INTEGER,
EMPLOYEE_WORK TEXT);

INSERT INTO EMPLOYEE VALUES
('1','MICHEAL',32,'ACCOUNTENCY'),
('2','HASSAN',21,'ENGINEER'),
('3','JOSEPH',43,'GRAPHIC DESGNER'),
('4','ANTONY',26,'FINANCE'),
('5','HASHAM',30,'SOFTWARE ENGINEER');

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE EMPLOYEE_AGE=21 AND EMPLOYEE_WORK='ENGINEER';